#!/bin/bash
set -e

CONFIG_PATH=/data/options.json

# Read the authorized_ips array and join with commas for Ganesha
AUTHORIZED_IPS=$(jq --raw-output '.authorized_ips | join(",")' $CONFIG_PATH)

# Read the export_folders array
EXPORT_FOLDERS=$(jq --raw-output '.export_folders[]' $CONFIG_PATH)

echo "[NFS] Starting NFS-Ganesha (Debian Mode)..."
echo "[NFS] Authorized IPs: ${AUTHORIZED_IPS}"
echo "[NFS] Export folders: $(jq --raw-output '.export_folders | join(", ")' $CONFIG_PATH)"

# 1. Start DBUS
echo "[NFS] Starting D-Bus..."
mkdir -p /var/run/dbus
if [ -e /var/run/dbus/pid ]; then rm /var/run/dbus/pid; fi
dbus-daemon --system --fork

# 2. Build Ganesha Configuration
CONF="/etc/ganesha/ganesha.conf"
mkdir -p /etc/ganesha

cat > $CONF <<EOF
###################################################
#     NFS-Ganesha Config Generated by Addon       #
###################################################

NFS_CORE_PARAM
{
    NFS_Port = 2049;
    NFS_Protocols = 4;
    Enable_NLM = false;
    Enable_RQUOTA = false;
}

NFSv4
{
    Grace_Period = 60;
    # Use numeric IDs to avoid ID mapping issues
    Only_Numeric_Owners = true;
}

EXPORT_DEFAULTS
{
    Squash = All_Squash;
    Anonymous_Uid = 0;
    Anonymous_Gid = 0;
}

NFS_KRB5
{
    Active_krb5 = false;
}

LOG {
    Default_Log_Level = WARN;
    COMPONENTS {
        TIRPC = FATAL;
        NFS_CB = FATAL;
        INIT = FATAL;
        DISPATCH = FATAL;
    }
}
EOF

# 4. Add Exports based on user selection
ID=10

while IFS= read -r FOLDER; do
    DIR="/$FOLDER"
    
    if [ -d "$DIR" ]; then
        echo "[NFS] Exporting: $DIR"
        
        cat >> $CONF <<EOF

EXPORT
{
    Export_Id = $ID;
    Path = "$DIR";
    Pseudo = "$DIR";
    FSAL { Name = VFS; }
    Access_Type = None;
    CLIENT
    {
        Clients = $AUTHORIZED_IPS;
        Protocols = 4;
        Access_Type = RW;
    }
}
EOF
        ID=$((ID+1))
    else
        echo "[WARN] Directory $DIR does not exist, skipping..."
    fi
done <<< "$EXPORT_FOLDERS"


# Create rpcbind socket directory so libtirpc can fall back to TCP (HAOS rpcbind)
mkdir -p /run/rpcbind

LOGFILE="/tmp/ganesha.log"
touch $LOGFILE
tail -F $LOGFILE &
TAIL_PID=$!

echo "[NFS] Launching Ganesha Daemon..."

/usr/bin/ganesha.nfsd -F -L $LOGFILE -f $CONF 2>&1 || true

echo "[NFS] Ganesha exited"
kill $TAIL_PID 2>/dev/null || true
